### ISSUE TITLE
bug? High Oven will not melt metals different from what is already inside.

### ISSUE THREAD

**Issue by mkire** [Ephys/TinkersSteelworks#108]
I'm using the current release on github and just built an eight block tall high oven, fed it some charcoal and gave it a duct to suck in ores from a chest. It's reached 4000C and melting things nicely. Except if i've got molten gold in there it won't melt anything besides gold and same for any other molten metal. Is this intended?

Using forge 1448 in java 8.

**Comment by Ephys** [comment]
Yes it was part of Toop's design to only allow steam and water in the high oven at the same time. The easy solution is to add a deep tank close to the high oven and pipe the liquid there

**Comment by mkire** [comment]
Really? I know i played the 1.6.4 version and it allowed you to smelt anything regardless of what was inside, it just wouldn't alloy stuff the way the smeltery does.

**Comment by Ephys** [comment]
I implemented it based on this comment https://github.com/Toops/TinkersSteelworks/blob/master/src/tsteelworks/blocks/logic/HighOvenLogic.java#L1177

**Comment by mkire** [comment]
ah, thank you.
