### ISSUE TITLE
Sulfur is not consumed when making steel

### ISSUE THREAD

**Issue by KnightMiner** [Ephys/TinkersSteelworks#110]
I've been using sulfur from Thermal Expansion as an oxidizer in making steel, and upon making the recipe, the sulfur is never consumed. I've tested the recipe with gunpowder and Thermal Expansion's pulverized coal and both of those are consumed, but even after making a full chest of iron ore into steel, not one piece of sulfur was used up.

If it helps, I am using version 1.1.1-17 for 1.7.10.

**Comment by kane-thornwyrd** [comment]
Like at all or sometimes it's still consumed ? If so, it's expected.

**Comment by Ephys** [comment]
It's because steel allows both dustSulfur and dustSulphur but only one of them has been registered as an oxidizer https://github.com/Ephys/TinkersSteelworks/blob/55be8da27ee3df877f288ed84ac6e8ed22a71a3c/src/main/java/toops/tsteelworks/common/core/TSContent.java#L210
