### ISSUE TITLE
Immersive Engineering Coal Coke in High Oven

### ISSUE THREAD

**Issue by aerialspring** [Ephys/TinkersSteelworks#113]
Hello! 

RailCraft coal coke works in the high oven, and is ore dict'd with Immersive Engineering coal coke. However, we do not have RailCraft in the pack, and the high oven isn't recognizing the IE coal coke. I'm not sure where I can add this - possibly with minetweaker/modtweaker, but would you be able to add this to the next update?

Thanks!

**Comment by Ephys** [comment]
Temporary fix:
mods.tsteelworks.highoven.addFuel(fuel, burn time, heat rate);

I'll oredict it for the next update

**Comment by aerialspring** [comment]
Perfect thanks!

On Monday, September 7, 2015, Guylian Cox <notifications@github.com> wrote:

> Temporary fix:
> mods.tsteelworks.highoven.addFuel(fuel, burn time, heat rate);
>
> I'll oredict it for the next update
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Ephys/TinkersSteelworks/issues/113#issuecomment-138354464>
> .
>


-- 
Noreen
