### ISSUE TITLE
Slabs are incorrectly implemented

### ISSUE THREAD

**Issue by KnightMiner** [Ephys/TinkersSteelworks#115]
Starting with the cracked limestone bricks slab, each slab name is shifted one over, meaning cracked limestone bricks slab is called "Limestone Paver Slab", paver is called road, etc. Additionally, the fancy scorched slab is incorrectly called "Chiseled Scorched Slab" These issues are caused by the file [here](https://github.com/Ephys/TinkersSteelworks/blob/2b39929060a6d1dafb74e3101bbb698c907d309d/src/main/java/toops/tsteelworks/common/core/TSContent.java) if it helps

Secondly, the crafting recipes are very unexpected (from [here](https://github.com/Ephys/TinkersSteelworks/blob/2b39929060a6d1dafb74e3101bbb698c907d309d/src/main/java/toops/tsteelworks/common/core/TSRecipes.java)), with the following strange occurrences:

* Creepy scorched and cracked scorched bricks cannot craft a slab
* Scorched stone gets creepy scorched slabs
* Scorched cobblestone gets scorched stone slabs
* Scorched paver gets scorched cobblestone slabs
* Scorched road gets scorched paver slabs
* Fancy scorched bricks get cracked scorched bricks slab
* Chiseled scorched bricks get scorched road slabs
* HighOven.Furnace.name (invalid block) gets chiseled scorched slabs
* All of the incorrectly named limestone slabs can be crafted from the same named blocks (changing the texture)

**Comment by Ephys** [comment]
Can you point out which version of TSteelworks you are using ? Fixing slabs is on my todo list but I thought I fixed the name issue already

**Comment by KnightMiner** [comment]
I'm using 1.1.1-17 for 1.7.10, as its the latest version on CurseForge.
