### ISSUE TITLE
Coal coke block uses incorrect OreDict name

### ISSUE THREAD

**Issue by KnightMiner** [Ephys/TinkersSteelworks#120]
Both Immersive Engineering and Railcraft use `blockFuelCoke` as the OreDict name for coal coke blocks, but [TSRecipes.java](/Ephys/TinkersSteelworks/tree/master/src/main/java/toops/tsteelworks/common/core/TSRecipes.java#L55) registers it as `blockCoke`, causing blocks of coal coke to not work as fuels

**Comment by ephys** [comment]
There you go :) http://tehnut.info/jenkins/view/Ephys/job/TSteelworks/20/

**Comment by KnightMiner** [comment]
Thanks for such a fast response!
