### ISSUE TITLE
Highoven doesn't use oredict Charcoal blocks

### ISSUE THREAD

**Issue by Arkandos** [Ephys/TinkersSteelworks#33]
TSteelworks-1.7.10-1.0.5.jar

The highoven only accepts TSteelworks charcoal blocks as fuel and not other mods charcoalblocks.

**Comment by Mochnant** [comment]
If it helps, this also occurs with Metallurgy 4 charcoal blocks.

**Comment by Ephys** [comment]
Wisthy's commit fixed it, closing
