### ISSUE TITLE
[Not important but nifty] Minetweaker Support

### ISSUE THREAD

**Issue by T10a** [Ephys/TinkersSteelworks#35]
Hello, will it be possible to implement code allowing custom Minetweaker recipes? I know ModTweaker supported Toops' Tinker's Steelworks in 1.6.4, but will you add native support for it?

**Comment by Ephys** [comment]
Complete as of latest commit https://github.com/Ephys/TinkersSteelworks/commit/27a5d10617c9aeafc0fb0cd21ea0e899de8356a7
