### ISSUE TITLE
Coal not fuel

### ISSUE THREAD

**Issue by Pilad** [Ephys/TinkersSteelworks#44]
Only charcoal fuel. Add coal please.

**Comment by Ephys** [comment]
Coal cannot be used in a high oven, this is intended. Only charcoal, alumentum and coal coke are allowed so far (but once we implement minetweaker support, you'll be free to change that)

.rar are a pain, can you pastebin that [and make a new ticket as this is a different issue] ?

Turbines receive steam & fluid alloys and separate the alloys (pipe in steam, pipe in alloy, pipe out components)

**Comment by Ephys** [comment]
Managed to open the rar, it's a cookiecore issue
https://github.com/Ephys/CookieCore/issues/2
