### ISSUE TITLE
Can't change iconography in High Oven Duct

### ISSUE THREAD

**Issue by Virtulox** [Ephys/TinkersSteelworks#45]
So I have a little problem, I can't change where the items are routed in the High Oven Duct. I can press the arrows but the icon inside the box won't change no matter what I do. Everything else seems to work and what I mean is that if I put gunpowder in the High Oven Duct, since the oxidizers icon  is the default one, the gunpowder will end up in the right slot in the High Oven. So basically I can't change WHERE items end up in the High Oven but they still do. I'm pretty sure this is caused by another mod.
I know you'll need some kind of Log or a mod list to find what the problem is but I don't really know where to find those in my minecraft directory.

Tinker's Steelworks Version: 1.7.10-1.0.6

**Comment by PiggyWhiskey** [comment]
I'm having the same issue.
Y level doesn't affect.

Solution from https://github.com/Ephys/TinkersSteelworks/issues/25

Break controller after placing the ducts, and re-form.
