### ISSUE TITLE
Steams output.

### ISSUE THREAD

**Issue by Pilad** [Ephys/TinkersSteelworks#46]
Make a separate output for the steams.As water leaves before heating.
The steam turbine does not work well ..

**Comment by Ephys** [comment]
Add a filter on your pipe, most mods support that. The steam is moved at the very bottom of the tank when produced to ensure pipes will try to pipe out that first so adding a filter should solve it.

**Comment by Pilad** [comment]
Not all pipes work with filters. Simply add interfaces only steam out.
