### ISSUE TITLE
Localize Vacuous in forge GUI

### ISSUE THREAD

**Issue by Adaptivity** [Ephys/TinkersSteelworks#49]
See: https://github.com/SlimeKnights/TinkersConstruct/blob/ed7e9dacb0b74e0a9bcb7be91f940d43eb8030f5/src/main/java/tconstruct/tools/gui/ToolStationGuiHelper.java#L147-L174

**Comment by Adaptivity** [comment]
@Ephys simple adding modifier.toolstation.vacuous in .lang file doesn't help.

**Comment by Ephys** [comment]
I know, that's why this issue isn't closed yet. Couldn't figure out how their localization system works

**Comment by Adaptivity** [comment]
Calling @bonii-xx ...

**Comment by Ephys** [comment]
Yeah I was gonna ask around on IRC but right now I've got to study, will do by the end of the week :3

**Comment by bonii-xx** [comment]
It's a hack that uses the keys used in the modifiers to get a localized string out of them because any other solution would be an api break.
