### ISSUE TITLE
Request: Dynamically sized Deep Tank GUI

### ISSUE THREAD

**Issue by PiggyWhiskey** [Ephys/TinkersSteelworks#50]
Currently it is accurately sized to the deep tank storage capacity.
However when starting out, I make extra Clear Glass purposely to over compensate the Deep Tank.
This leaves several buckets not visible on the GUI. (First ~5 Buckets are out of range. Next 5-10 is about 1/2 pixels high.)

Downside is I can't move fluids around to re-pour into a casting basin if it isn't quite full.

**Comment by Ephys** [comment]
That must be a reaaally big tank, I'll see if a can manage to add a zoom button or something

**Comment by PiggyWhiskey** [comment]
5x5x5. Over cooked the scorched brick. Didn't want it to go to waste. With
Clear glass too.

**Comment by Ephys** [comment]
http://i.imgur.com/Ay6spi8.png -> http://i.imgur.com/8l8vLVH.png (with zoom)

this took me ages of ctrl+scrolling but the tank is enormous
