### ISSUE TITLE
Ex Astris Issue

### ISSUE THREAD

**Issue by Herekar** [Ephys/TinkersSteelworks#51]
had this happen to me this morning http://pastebin.com/nWavHQCc and was ablt to fix it in the ex astris config for now b setting it as follows  B:"Tsteelworks melting allowed"=false
I'm still new to all of this so i am not entirely sure what that does or does not allow but figured a heads up would be helpful.

**Comment by Ephys** [comment]
Yeah I reworked the lib to prepare the modtweaker support. I'll write a decent API that will prevent this from happening again in the future though (but in the meantime, Ex Astris needs to update its TSteelwork references)

**Comment by MikeLydeamore** [comment]
Speaking of this, I've been using your shiny new API, but have gotten nothing but crashes. 
Log: http://pastebin.com/pfGex3ni

I've tried doing this a number of ways, using ISmeltingRegistry.INSTANCE as well as a getInstance, both ot the same effect.
Code here: https://github.com/MikeLydeamore/Ex-Astris/blob/master/src/main/java/ExAstris/Bridge/TSteelworks.java
Wondering if you can shine some light in on what I'm doing wrong?

**Comment by Ephys** [comment]
One of the itemstacks you're passing has a null item (probably one of the GameRegistry.findItem queries returns null)

As a result, the registry implementation which uses a hashmap fails to get the hash of the item as it is null
https://github.com/Ephys/CookieCore/blob/1.7/src/main/java/nf/fr/ephys/cookiecore/util/HashedItemStack.java#L22
