### ISSUE TITLE
Crash with Railcraft_1.7.10-9.5.0.0

### ISSUE THREAD

**Issue by Njet75** [Ephys/TinkersSteelworks#60]
Got this crash
http://pastebin.com/31fLPdHb
Sorry for no FML log it was to big for pastebin.
/Njet

**Comment by Yulife** [comment]
Use the latest version from the jenkins.

**Comment by Ephys** [comment]
You're also going to need the newer cookiecore from the same jenkins
http://tehnut.info/jenkins/job/CookieCore/
http://tehnut.info/jenkins/job/TSteelworks/

**Comment by Njet75** [comment]
Thanks for superfast support.
/Njet
