### ISSUE TITLE
Ink Sacs turn/unify into Bonemeal

### ISSUE THREAD

**Issue by stardustrider** [Ephys/TinkersSteelworks#62]
If you kill a squid, it drops bonemeal (or it drops ink sacs, which turn into bonemeal almost instantly).

If you hold ink sacs, they'll change to bonemeal in your inventory fairly quickly (very similar to GregTech's oredictionary unification behaviour).

Using the 1.1.0-6 build from: http://tehnut.info/jenkins/job/TSteelworks/

**Comment by Ephys** [comment]
Are you sure that's from us ? I can't reproduce that bug in my dev env :/

**Comment by stardustrider** [comment]
It could be a weird mod compatibility issue, but as soon as I removed Steelworks, it stopped occuring.

**Comment by Ephys** [comment]
What mods do you have installed ?

**Comment by stardustrider** [comment]
Prepare thine self!

https://www.dropbox.com/s/5jrqbsj8j00ftoa/Modded%20%28v4%29%20-%20Mod%20List.xlsx?dl=0

**Comment by Biofusionz** [comment]
Same issue here. I have a few of the same mods. AE, AE:Extra Cells, Bibliocraft and addons, BoP, Buildcraft, Carpenter's Blocks, all CoFH mods, Cookie Core, Extra Utilities, Forestry, FMP, iChunUtil, IC2. Gregtech, JABBA, Mantle, MFR, MineTweaker, ModTweaker, MobiusCore, NEI, OpenBlocks, OpenComputers, OpenModsLib, Railcraft, Steves Carts, Tinkers' Construct, Iguana Tinker Tweaks, Tinkers' Steelworks, Tinkers' Mechworks, Translocator.

That narrows down the list a little bit. For now I've just made a recipe for Ink using minetweaker Bonemeal-ink

**Comment by UndeadZeratul** [comment]
I'm fairly certain this is the work of GregTech's unification.

**Comment by stardustrider** [comment]
Disabling the unification specifically for bonemeal and ink saks didn't stop it from occuring. That was my first port of call too when I noticed it occuring. That, and the fact it only occurs when Steelworks is present points to it not being Greg.

**Comment by Biofusionz** [comment]
I did some testing and found out it is GT, but only happens when TSteelworks is installed. I fixed it by changing:
B:dustBone_false=false to
B:dustBone_false=true in the GT unification config.

It's weird how it's turned off by default.

**Comment by Ephys** [comment]
I wonder if it isn't caused by this: https://github.com/Ephys/TinkersSteelworks/blob/672b129840f635864b0f1db86fb55ed684e1ebdc/src/main/java/toops/tsteelworks/common/plugins/tconstruct/TCSmeltery.java#L122
