### ISSUE TITLE
No steam texture – crash when boil water to steam

### ISSUE THREAD

**Issue by DcNdrew** [Ephys/TinkersSteelworks#63]
I don't have more mods which use steam, so there's no texture for it. When the high over has steam and I right click on the controller, the Minecraft crashes. As soon as I install a mod with steam, MC has no problem.

**Comment by Ephys** [comment]
What version are you using ? I'm aware of the issue but I though I fixed it

**Comment by DcNdrew** [comment]
The latest.
TSteelworks-1.7.10-1.0.7.jar

**Comment by Ephys** [comment]
Can you try the version from the jenkins and tell us if it's still happening ?
http://tehnut.info/jenkins/job/CookieCore/
http://tehnut.info/jenkins/job/TSteelworks/

**Comment by DcNdrew** [comment]
Works nice, thank you! :)
