### ISSUE TITLE
Register limestone as limestone in oredictionary?

### ISSUE THREAD

**Issue by ChatFawkes** [Ephys/TinkersSteelworks#66]
Hello,
I was wondering if you could possibly register the limestone block as `limestone` in addition to `blockLimestone` in the ore-dictionary? This way Chisel would be compatible with the limestone added by this mod.

**Comment by wisthy** [comment]
@ChatFawkes are you sure the ore-dictionary name in Chisel is "limestone"? Based on #12, it's not really clear.

**Comment by Ephys** [comment]
@wisthy's pull request fixed it, and as a bonus: http://screencloud.net/v/4xmt http://screencloud.net/v/4MQo
