### ISSUE TITLE
Entity ID Conflict

### ISSUE THREAD

**Issue by buymytoasters** [Ephys/TinkersSteelworks#69]
Hey guys and or gals.  Thanks for taking up 1.7.10 development on Steelworks <3

Running into an entity ID conflict on load.  Some quick searching didn't show me an easy way to fix this myself.  Several posts I found suggested that there is a way to implement entities in mods that won't cause this conflict, or a fast workaround would be a config option to change the entity ID manually.

Pastebin: http://pastebin.com/j2JcCFw9

If you need any additional testing, info, or logs, let me know.

-bmt

**Comment by Adaptivity** [comment]
Don't use global entities. It's evil stuff. Use mod-entities instead.
