### ISSUE TITLE
"Ingots per ore" don't work

### ISSUE THREAD

**Issue by renard162** [Ephys/TinkersSteelworks#70]
I'm using Tsteelworks v1.1.0-6 for railcraft compatibility and I want to put 3 ingot per ore but the config file don't work, even with "Ingots per ore"=3 High Oven produces 2 ingots.

Minecraft: 1.7.10
Forge: 10.13.2.1291
Mods (from dump file):
TConstruct,Tinkers' Construct,1.7.10-1.8.2.build858
TSteelworks,Tinkers' Steelworks,1.7.10-1.1.0

**Comment by kotoroshinoto** [comment]
This is happening to me as well.using TSteelworks-1.7.10-1.1.0-7.jar
