### ISSUE TITLE
block of charcoal not accepted

### ISSUE THREAD

**Issue by Kenshij** [Ephys/TinkersSteelworks#71]
Hello,

i have metallurgy mod installed, it overides the recipe for block of charcoal. The high oven don't accept it. I think is hard coded to the tinkersteelwork block of charcoal.

Can you make it mod idependend or add a config option which fuel the high oven accept.

**Comment by wisthy** [comment]
We use every block of charcoal defined using the OreDictionary.

OreDictionary.getOres("blockCharcoal")

So, it's probably that the OreDictionary name in metallurgy is not the same.

**Comment by Ephys** [comment]
What version of the mod are you using ? This should be fixed in the version on the jenkins (see the readme.md)

**Comment by Kenshij** [comment]
Oh i will report it to the other mod, thanks for the support^^
[
{
  "modid": "Metallurgy",
  "name": "Metallurgy 4",
  "description": "Metallurgy",
  "credits": "",
  "logoFile": "",
  "version": "4.0.6",
  "mcversion": "1.7.10",
  "url": "",
  "updateUrl": "",
  "authorList": [
    "Team Metallurgy"
  ],
  "screenshots": [
  ],
  "parent":"",
  "requiredMods" : [
     "MetallurgyCore@[4.0.4,]"
  ],
  "dependencies": [
    "MetallurgyCore@[4.0.4,]",
    "Botania",
    "TConstruct"
   ],
  "dependants": [
    "UndergroundBiomes"
   ],
  "useDependencyInformation": "true"
}
]

**Comment by wisthy** [comment]
@Kenshij the question of @Ephys was about which version of TSteelworks are you using? The OreDictionnary is not an old feature.

**Comment by Kenshij** [comment]
TSteelworks-1.7.10-1.0.6.jar
