### ISSUE TITLE
Steel recipe bug

### ISSUE THREAD

**Issue by zerotheliger** [Ephys/TinkersSteelworks#73]
The High Oven is running off one redstone, one gunpowder, one sand
can run as much iron as i want through the high oven
once i break the controller the redstone gunpowder and sand is gone, but i still have any steel i poured out in the mean time

also the controller will not respond to a redstone signal once it gets charcoal its on

**Comment by wisthy** [comment]
it should be fixed with the latest version on Jenkins. 

To be tested

**Comment by Ephys** [comment]
I can confirm, it has been fixed by your commit
