### ISSUE TITLE
Steel ingot output is wrong

### ISSUE THREAD

**Issue by simlhawk** [Ephys/TinkersSteelworks#77]
If I put either iron ingots or iron ore, it doesn't matter. I will always get 7 ingots worth out of an iron item.

This is my config: http://pastebin.com/Avr0C3ey

Not sure why this is happening. I currently have the config set to 1 ingot per ore.

Edit: Currently using TSteelworks-1.7.10-1.1.0-7.jar

**Comment by Ephys** [comment]
Same issue as #81, it has been fixed :)
