### ISSUE TITLE
book shows scorched stone in seared stone recipe

### ISSUE THREAD

**Issue by kotoroshinoto** [Ephys/TinkersSteelworks#78]
(also it seems like the reagents are not used up at all, it just melts the stone into seared stone)

**Comment by TorakWolf** [comment]
I don't see any uses for molten scorched stone, so it's not that strange that it turns into seared stone when smelted. Besides, I still prefer just tossing seared stone on bricks. It's so easy... Unless you want the clay to something else.

**Comment by Ephys** [comment]
I believe it's supposed to output scorched bricks as an item not as a fluid (which is 100% possible, just need to add the recipe)
