### ISSUE TITLE
Fundamental Recipe Bug

### ISSUE THREAD

**Issue by Voidi** [Ephys/TinkersSteelworks#81]
It seems ther is a game breaking bug how the recipes are handled.
If you want to make steel, it make 1000mB Molten steel, regardless what part of iron you put in.

I think this behaviour is caused by the highoven, to only check for the fluid type, not the amout.
https://github.com/Ephys/TinkersSteelworks/blob/master/src/main/java/toops/tsteelworks/common/blocks/logic/HighOvenLogic.java#L335

**Comment by Ephys** [comment]
Yup, I forgot to add a mix.amount = melt.amount
