### ISSUE TITLE
High oven won't smelt unless GUI is open.

### ISSUE THREAD

**Issue by 0PT1K5** [Ephys/TinkersSteelworks#84]
MC:1.7.10
Forge: 10.13.2.1291
Tconstuct: 1.8.3b
Tsteelsowrks: 1.1.0-6

New Items will only be pulled into the High Oven when the GUI is open, not sure if it has to do with the controller placement above ducts and drains.
It is also in an RFTools dimension.

![2015-03-29_20 26 52](https://cloud.githubusercontent.com/assets/11709488/6887316/32b3bd60-d653-11e4-8557-737145b5cd5e.png)

![2015-03-29_20 27 02](https://cloud.githubusercontent.com/assets/11709488/6887320/704bb43e-d653-11e4-8171-f697e9149f3e.png)

![2015-03-29_20 27 08](https://cloud.githubusercontent.com/assets/11709488/6887322/8f34a3e2-d653-11e4-9553-c8ede4e928c5.png)

**Comment by Ephys** [comment]
The absolute what

That's some serious bug, I did reproduce it. I'll try to fix it
