### ISSUE TITLE
Crash with Cookie Core

### ISSUE THREAD

**Issue by TorakWolf** [Ephys/TinkersSteelworks#85]
This is the crash:

http://pastebin.com/x68SQwJ7

**Comment by Ephys** [comment]
Hello,

use this version: http://tehnut.info/jenkins/job/TSteelworks/
(Dupe #60)

**Comment by TorakWolf** [comment]
This was fast!!!

**Comment by Ephys** [comment]
Email notifications and it was already fixed :p

**Comment by TorakWolf** [comment]
No, I understood that part. Just didn't expect that you would be online.

**Comment by TorakWolf** [comment]
Oh, I forgot how to craft cement, can you remember me? It was something with limestone...
