### ISSUE TITLE
Fatal Crash On Startup

### ISSUE THREAD

**Issue by BonesTheRabbit** [Ephys/TinkersSteelworks#87]
This is with only the required mods enabled. Just thought you should know.

Minecraft version: 1.7.10
Forge version: 1364
Tinker's Steelworks version: 1.0.7
Tinker's Construct version: 1.8.3b
CookieCore version: 1.3.1-7
Mantle version: 0.3.2

Crash report: http://pastebin.com/j511XU16

**Comment by Ephys** [comment]
Ah, you upgraded cookiecore but not TSteelworks (because it's not on curseforge), you can get it here http://tehnut.info/jenkins/job/TSteelworks/

**Comment by BonesTheRabbit** [comment]
Thanks kindly! Sorry for the mistake.
