### ISSUE TITLE
Having some troubles....

### ISSUE THREAD

**Issue by BohemianRahpGod** [Ephys/TinkersSteelworks#88]
Hey my howmdawg!
So I was trying to reboot my modpack I haven't worked on in a while, and whenever I load up minecraft, I get a crash, pointing towards Steelworks. If I remove the mod, though, everything goes well. I was wondering if I could get some help? 

Crash Log --> pastebin.com/FEbqQrMT
Mod list screenshot is attached below.
Thanks!
![image](https://cloud.githubusercontent.com/assets/11903414/7102826/e223ab08-e05c-11e4-90de-e89db00e8b17.png)

**Comment by Ephys** [comment]
Duplicate #87 follow link
