### ISSUE TITLE
Crash on server and client startup

### ISSUE THREAD

**Issue by LordPinkerton** [Ephys/TinkersSteelworks#89]
I'm getting a crash on startup.

http://pastebin.com/L2djE4Rv

**Comment by wisthy** [comment]
Info extracted from the pastebin:
* TSteelworks{1.7.10-1.0.0} [Tinkers' Steelworks] (TSteelworks-1.7.10-1.0.0.jar)
* TConstruct{1.7.10-1.8.3.build919} [Tinkers' Construct] (TConstruct-1.7.10-1.8.3b.jar)

@LordPinkerton could you tell us if it is in a modpack? if yes, which one? If no, try updating to the latest version

**Comment by LordPinkerton** [comment]
It's not in an official pack, just a personal one. I really do feel foolish now though, as I could have sworn I had put in TSteelworks-1.7.10-1.1.0-13. I appreciate you taking a look and pointing that out for me.

**Comment by Ephys** [comment]
They probably changed the return type or something on TConstruct's end, we just need to update the deps

**Comment by LordPinkerton** [comment]
If that's needed. As I said, my crash was caused apparently by just having an outdated copy of the mod. Once I put in the correct version, it started up like a charm.

**Comment by Ephys** [comment]
Oh, sorry then you're right this is closed ^^'
