### ISSUE TITLE
Ex Nihilo ores output too much

### ISSUE THREAD

**Issue by Timeslice42** [Ephys/TinkersSteelworks#97]
If I have "Ingots per ore" set to 3.0 then vanilla iron ore gives three ingots, but the ex nihilo iron ore (dust) gives nine ingots. If I have "Ingots per ore" set to 1.0 then the ex nihilo ore gives three ingots, but the vanilla ore only gives 1.

On a side note if I set the ingots per ore to zero does it waste the ore, or does it not try to smelt it? It might be useful if I could just change the high oven into an alloys only machine.

**Comment by Ephys** [comment]
What's your TSteelworks version ? I thought I fixed this

**Comment by Timeslice42** [comment]
I'm using TSteelworks-1.7.10-1.1.0-14

**Comment by Timeslice42** [comment]
Have you had any traction yet with this issue?

**Comment by Ephys** [comment]
No but I'll look into it. Maybe it's adding its recipe to both TSteelworks and TConstruct and there is a conflict of some sort.
